### PR TITLE
Adape go2sky v1.0.0

### PR DESCRIPTION
**Pull request by mrproliu**

### CODE REVIEW

**Comment by mrproliu** [comment]
Hi, @kezhenxu94. I found an error when upgrading the `go-micro` plugin to the newest `go2sky` version. I think the current gRPC version of `goapi` conflicts with `go-micro`. 
Current `go-micro` plugin needs gRPC version `v1.26.0` and the `goapi` is using gRPC version `1.36.0`. Could you help to see?

**Comment by wu-sheng** [comment]
> Hi, @kezhenxu94. I found an error when upgrading the `go-micro` plugin to the newest `go2sky` version. I think the current gRPC version of `goapi` conflicts with `go-micro`.
> Current `go-micro` plugin needs gRPC version `v1.26.0` and the `goapi` is using gRPC version `1.36.0`. Could you help to see?

Could we upgrade the go-micro version?

**Comment by mrproliu** [comment]
> > Hi, @kezhenxu94. I found an error when upgrading the `go-micro` plugin to the newest `go2sky` version. I think the current gRPC version of `goapi` conflicts with `go-micro`.
> > Current `go-micro` plugin needs gRPC version `v1.26.0` and the `goapi` is using gRPC version `1.36.0`. Could you help to see?
> 
> Could we upgrade the go-micro version?

Current `1.18.0` is `go-micro` lastest v1 release. Unless we only support V2 or later, I haven't tried which V2 version will be compatible.

**Comment by kezhenxu94** [comment]
I'd rather we drop support for go-micro 1.x as its latest version had been v3 and the last version of 1.x is ~1.5 year ago,

**Comment by wu-sheng** [comment]
> I'd rather we drop support for go-micro 1.x as its latest version had been v3 and the last version of 1.x is ~1.5 year ago,

Make sense to me too. go ecosystem is usually upgrading to the latest, at least today, they still are.

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
@arugal Do you have time to recheck?

**Review by arugal — APPROVED** [review]
LGTM

**Pull request merged**
