### PR TITLE
Make plugins support correlation protocol

### PR DESCRIPTION
**Pull request by mrproliu**
Follow https://github.com/SkyAPM/go2sky/pull/91#issuecomment-792274851, Support correlation context protocol to go2sky plugins.

### CODE REVIEW

**Comment by arugal** [comment]
LGTM, please give me some time to release `go2sky` 1.0.0, I've been a little busy lately :)

**Comment by wu-sheng** [comment]
@arugal I think we should merge this first, and update the dependency again after the release happens? Otherwise, this project's current master is not working with the latest core.

**Comment by arugal** [comment]
> @arugal I think we should merge this first, and update the dependency again after the release happens? Otherwise, this project's current master is not working with the latest core.

Agree :)

**Review by arugal — APPROVED** [review]
LGTM, @mrproliu please update the [commitid](https://github.com/apache/skywalking/blob/master/test/e2e/e2e-test/docker/go/Dockerfile.go#L18) in E2E :)

**Pull request merged**
