### PR TITLE
Support use zap to transmit trace context to log

### PR DESCRIPTION
**Pull request by mrproliu**
See https://github.com/SkyAPM/go2sky/issues/104
Support the `zap` log framework

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]
LGTM. @arugal Please recheck.

**Comment by wu-sheng** [comment]
Should we consider releasing 1.1.0?

**Review by arugal — APPROVED** [review]
LGTM,  agreed to release v1.0.1 :)

**Comment by wu-sheng** [comment]
`v1.0.1` or `v1.1.0`. I assume as new features and versions involved, we should consider 1.1.0

**Pull request merged**
